### ISSUE TITLE
Which database for users

### ISSUE THREAD

**Issue by praetorianer777** [praetorianer777/qa-kb#4]
Should we use redis with persistance as storage for user information and permission stuff?
It would be only for management, the real data are stored in md files.

What's your opinion on this?

**Comment by Cloudster1** [comment]
Redis is not suited for this case imo.
We need a database which allows persistence and provides the ability to manages users and access rights on a per user basis.
Therefore i don not see any reason why we should not use a RDBMS for user management.

**Comment by praetorianer777** [comment]
And do we want to use ORM for this?

**Comment by Cloudster1** [comment]
I guess so

**Comment by praetorianer777** [comment]
@woelfin89  please research the advantages and disadvantages different databases have for this case.
